[package]
name = "serde_nom_csv"
version = "0.1.0"
authors = ["Dragonink"]
description = "Custom Serde library for CSV using Nom"
repository = "https://github.com/Dragonink/serde_nom_csv"
categories = ["parser-implementations"]
keywords = ["serde", "nom", "csv"]
edition = "2021"
publish = false

[dependencies]
nom = "7"
serde = "1"
